[package]
name = "rCURL"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
reqwest = { version = "0.12.7", features = ["json", "multipart", "blocking", "stream"] }
serde_json = "1.0.128"
tokio = { version = "1", features = ["full"] }
